config/routes.rb
Rails.application.routes.draw do
  get 'machine_list/index'

  get 'tarning/index'

  devise_for :users, controllers: {sessions: "users/sessions" , registrations: "users/registrations"}
  resources :homes
  resources :person_infos
  resources :machine_lists
  resources :permission_sheet

  resources :sensors do
    resources :sensor_logs
  end

  match 'sendlog', :to => 'sensor_logs#create', :via => [:get, :post]

  root to: "homes#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
  end
end

app/models/card.rb
class Card < ActiveRecord::Base

  belongs_to :person_info

end

app/models/machine_detail.rb
class MachineDetail < ActiveRecord::Base
end

app/models/machine_role.rb
class MachineRole < ActiveRecord::Base
end

app/models/page_manage_path.rb
class PageManagePath < ActiveRecord::Base
end

app/models/permission_sheet.rb
class PermissionSheet < ActiveRecord::Base
  has_many :users
end

app/models/person_info.rb
class PersonInfo < ActiveRecord::Base
	belongs_to :user
  has_many :cards
	def self.myacount(userID)
	  self.where(userId: userID).take
	end
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  validates_presence_of :name, :api_key

  has_many :sensor_logs

end

app/models/sensor_log.rb
class SensorLog < ActiveRecord::Base

  belongs_to :sensor

end

app/models/socket_client.rb
class SocketClient < ActiveRecord::Base
	def self.givecommand(command)
		ip = '192.168.4.1'
		port = 4000
		tcpClient = TCPSocket.new ip, port
		tcpClient.print(command)
	end
private
	def client
		
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :personInfo
  belongs_to :permission_sheet, :foreign_key => 'permissionId'

  def self.resourceId(params)
		self.select(:id).where(email: params[:user][:email]).take.id
	end

  def self.saveSuperUserPermission(id)
  	if id == 1
        currentUser = User.find(id)
        currentUser.update(:permissionId => id)
  		return id
  	else
       id = 4
       currentUser.update(:permissionId => id)
  		return id
  	end
  end
end

app/models/work_shop_sheet.rb
class WorkShopSheet < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index
  end

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

  include SensorsHelper

  def index
    @sensors = Sensor.all
  end

  def show
    @sensor = Sensor.find(params[:id])
  end

  def new
    @sensor = Sensor.new
  end

  def create
    @sensor = Sensor.create(sensor_params)
    @sensor.api_key = generate_api_key
    if @sensor.save
      redirect_to sensor_path(@sensor.id), notice: '新增 Sensor 資料成功'
    else
      render :new
    end
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])
    # @sensor.api_key = generate_api_key if @sensor.api_key.to_s == ""
    if @sensor.update(sensor_params)
      redirect_to sensor_path(@sensor.id), notice: '修改 Sensor 資料成功'
    else
      render :edit
    end
  end

  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy
    redirect_to sensor_path, alert: 'Sensor 資料已刪除'
  end

private

  def sensor_params
    params.require(:sensor).permit(:name, :description, :v1_name, :v1_unit, :v2_name, :v2_unit)
  end

end

app/controllers/tarning_controller.rb
class TarningController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/machine_list_helper.rb
module MachineListHelper
end

app/helpers/permission_sheet_helper.rb
module PermissionSheetHelper
end

app/helpers/person_infos_helper.rb
module PersonInfosHelper
end

app/helpers/sensor_logs_helper.rb
module SensorLogsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper

  def generate_api_key(size = 16)
    alphas = ('0'..'9').to_a + ('A'..'Z').to_a
    new_key = (1..size).map {alphas[Kernel.rand(36)]}.join

    # 用遞迴方式處理碰撞
    new_key = generate_api_key if Sensor.find_by_api_key(new_key)
    return new_key
  end

end

app/helpers/tarning_helper.rb
module TarningHelper
end

app/views/sensors/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>修改</h1>

  <hr>
  <%= form_for @sensor, :method => :patch, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :name, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :name, input_html: {class: "form-control"}, size: 60 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :description, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_area :description, cols: 60, rows: 5, input_html: {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :v1_name, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :v1_name, input_html: {class: "form-control"}, size: 40 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :v1_unit, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :v1_unit, input_html: {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :v2_name, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :v2_name, input_html: {class: "form-control"}, size: 40 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :v2_unit, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :v2_unit, input_html: {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-8 col-md-offset-2">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/sensors/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= button_to 'New Sensor', new_sensor_path, :method => :get, class: 'btn btn-primary' %>
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-striped table-bordered">
    <thead>
    <tr class="bg-primary">
      <th>#</th>
      <th>Name</th>
      <th>Created</th>
      <th>Updated</th>
      <th>API Key</th>
      <th>Data Cnt.</th>
    </tr>
    </thead>
    <tbody>
      <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.id %></td>
        <td><%= link_to sensor.name, sensor_path(sensor.id) %></td>
        <td><%= sensor.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= sensor.updated_at.strftime("%Y-%m-%d") %></td>
        <td><%= sensor.api_key %></td>
        <td><%= sensor.sensor_logs.count %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/sensors/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>新增 Sensor</h1>

  <hr>
  <%= form_for @sensor, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :name, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :name, input_html: {class: "form-control"}, size: 60 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-2">
        <%= f.label :description, input_html: {} %>
      </div>
      <div class="col-md-4">
        <%= f.text_area :description, cols: 60, rows: 5, input_html: {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-8 col-md-offset-2">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/sensors/show.html.erb
<div class="row">
  <div class="col-md-1">
    <%= button_to 'Edit', edit_sensor_path, :method => :get, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-11">
    <%= button_to 'View Logs', sensor_sensor_logs_path(@sensor), :method => :get, class: 'btn btn-primary' %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <h3>Sensor detail</h3>

    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><label>Sensor ID</label></td>
          <td><%= @sensor.id %></td>
        </tr>
        <tr>
          <td><label>Sensor Name</label></td>
          <td><%= @sensor.name %></td>
        </tr>
        <tr>
          <td><label>Description</label></td>
          <td><%= @sensor.description %></td>
        </tr>
        <tr>
          <td><label>API Key</label></td>
          <td><%= @sensor.api_key %></td>
        </tr>
        <tr>
          <td><label>Created</label></td>
          <td><%= @sensor.created_at %></td>
        </tr>
        <tr>
          <td><label>Updated</label></td>
          <td><%= @sensor.updated_at %></td>
        </tr>
        <tr>
          <td><label>v1 Name</label></td>
          <td><%= @sensor.v1_name %></td>
        </tr>
        <tr>
          <td><label>v1 Unit</label></td>
          <td><%= @sensor.v1_unit %></td>
        </tr>
        <tr>
          <td><label>v2 Name</label></td>
          <td><%= @sensor.v2_name %></td>
        </tr>
        <tr>
          <td><label>v2 Unit</label></td>
          <td><%= @sensor.v2_unit %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-6">

    <h3>Data log (Last 10)</h3>

    <table class="table table-hover table-striped table-bordered">
      <thead>
        <tr class="bg-primary">
          <th>#</th>
          <th><%= if @sensor.v1_name.present? then @sensor.v1_name else 'N/A' end %> (<%= if @sensor.v1_unit.present? then @sensor.v1_unit else '*' end %>)</th>
          <th><%= if @sensor.v2_name.present? then @sensor.v2_name else 'N/A' end %> (<%= if @sensor.v2_unit.present? then @sensor.v2_unit else '*' end %>)</th>
          <th>Created</th>
        </tr>
      </thead>
      <tbody>
    <% @sensor.sensor_logs.order('id DESC').limit(10).each_with_index do |row, idx| %>
        <tr>
          <td><%= idx + 1 %></td>
          <td><%= row.v1 %></td>
          <td><%= row.v2 %></td>
          <td><%= row.created_at %></td>
        </tr>
    <% end %>
      </tbody>
    </table>

  </div>
</div>