config/routes.rb
Rails.application.routes.draw do
  get 'machine_list/index'

  get 'tarning/index'

  devise_for :users, controllers: {sessions: "users/sessions" , registrations: "users/registrations"}
  resources :homes
  resources :person_infos
  resources :machine_lists
  resources :permission_sheet

  resources :sensors do
    resources :sensor_logs
  end

  match 'sendlog', :to => 'sensor_logs#create', :via => [:get, :post]

  root to: "homes#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
  end
end

app/models/card.rb
class Card < ActiveRecord::Base

  belongs_to :person_info

end

app/models/machine_detail.rb
class MachineDetail < ActiveRecord::Base
end

app/models/machine_role.rb
class MachineRole < ActiveRecord::Base
end

app/models/page_manage_path.rb
class PageManagePath < ActiveRecord::Base
end

app/models/permission_sheet.rb
class PermissionSheet < ActiveRecord::Base
  has_many :users
end

app/models/person_info.rb
class PersonInfo < ActiveRecord::Base
	belongs_to :user
  has_many :cards
	def self.myacount(userID)
	  self.where(userId: userID).take
	end
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  validates_presence_of :name, :api_key

  has_many :sensor_logs

end

app/models/sensor_log.rb
class SensorLog < ActiveRecord::Base

  belongs_to :sensor

end

app/models/socket_client.rb
class SocketClient < ActiveRecord::Base
	def self.givecommand(command)
		ip = '192.168.4.1'
		port = 4000
		tcpClient = TCPSocket.new ip, port
		tcpClient.print(command)
	end
private
	def client
		
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :personInfo
  belongs_to :permission_sheet, :foreign_key => 'permissionId'

  def self.resourceId(params)
		self.select(:id).where(email: params[:user][:email]).take.id
	end

  def self.saveSuperUserPermission(id)
  	if id == 1
        currentUser = User.find(id)
        currentUser.update(:permissionId => id)
  		return id
  	else
       id = 4
       currentUser.update(:permissionId => id)
  		return id
  	end
  end
end

app/models/work_shop_sheet.rb
class WorkShopSheet < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/machine_list_helper.rb
module MachineListHelper
end

app/helpers/person_infos_helper.rb
module PersonInfosHelper
end

app/helpers/sensor_logs_helper.rb
module SensorLogsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper

  def generate_api_key(size = 16)
    alphas = ('0'..'9').to_a + ('A'..'Z').to_a
    new_key = (1..size).map {alphas[Kernel.rand(36)]}.join

    # 用遞迴方式處理碰撞
    new_key = generate_api_key if Sensor.find_by_api_key(new_key)
    return new_key
  end

end

app/helpers/tarning_helper.rb
module TarningHelper
end

app/views/common/_footer.html.erb
<hr class="container-inverse">
<div class="container">
  Page show time: <%= Time.now %>
</div>

app/views/common/_navbar.html.erb
<div class="container-inverse">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'GWSecurity', root_path, class: 'navbar-brand' %>
      </div>

      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="nav navbar-nav navbar-left">
          <li> <%= link_to('Sensors', sensors_path, :method => :get) %> </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to('Home', homes_path, :method => :get) %> </li>

          <% if current_user %>

          <li> <%= link_to('PersonInfo', person_infos_path, :method => :get) %> </li>
          <li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  </li>

          <% else %>

          <li> <%= link_to('Login', new_user_session_path, :method => :get) %> </li>
          <li> <%= link_to('Sign up', new_user_registration_path, :method => :get) %> </li>

          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GWSecurity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "common/navbar" %>

<div class="container">
  <%= notice_message %>
  <%= yield %>
</div>
<%= render "common/footer" %>

</body>
</html>